### ISSUE TITLE
Updation of README

### ISSUE THREAD

**Issue by shahenshah99** [vaib25vicky/awesome-mobile-security#1]
Hey, I have created a vulnerable android app, and it'd be nice if you could add that to your repo.
Here's the link to the app
https://github.com/shahenshah99/VulnDroid

**Comment by vaib25vicky** [comment]
Looks cool, including in the list.

**Comment by shahenshah99** [comment]
It'd be great if you could just change the name to VulnDroid - The name of the CTF App
