### ISSUE TITLE
[Tool Android] RMS - Runtime Mobile Security

### ISSUE THREAD

**Issue by m0bilesecurity** [vaib25vicky/awesome-mobile-security#6]
I would like to add [RMS - Runtime Mobile Security](https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security) in the Dynamic Analysis Tools section.

Runtime Mobile Security (RMS) 📱🔥 is a powerful web interface that helps you to manipulate Android Java Classes and Methods at Runtime

Many thanks!

**Comment by vaib25vicky** [comment]
Thanks for your contribution. I've added the RMS tool.

**Comment by m0bilesecurity** [comment]
many thanks!
